osism/k8s-capi-images

- .flake8
- .github/workflows/check-python-syntax.yml
> Add 'Check python syntax' workflow

- extra_vars_openstack_118.json
- extra_vars_openstack_119.json
- extra_vars_openstack_120.json
- extra_vars_openstack_121.json
- src/update-extra-vars.py
> Prettify json

- .cirrus.yml
> Fix changesInclude after file rename

- .github/workflows/update-extra-vars.yml
> github: remove debug output from 'Update extra_vars_X.json versions' workflow

- .github/workflows/update-extra-vars.yml
- scripts/run-update-extra-vars.sh
> Add run-update-extra-vars.sh script

- .cirrus.yml
- README.md
- extra_vars_openstack_flatcar.env
We do not use it and it does not build without additional effort.
> Remove Flatcar for the moment

- README.md
> README: add commercial support section

- .cirrus.yml
- extra_vars_openstack_ubuntu_122.json
> Add version 1.22.0

- .github/workflows/update-extra-vars.yml
- .github/workflows/update-image-builder-submodule.yml
> github: rename bot

- README.md
> README: add 1.22

- .cirrus.yml
> Upload X.Y.Z as well

- .github/workflows/update-image-builder-submodule.yml
> github: update the submodule every 6 hours

- .github/workflows/sync-with-upstream.yml
> github: fix commit message

- extra_vars_openstack_flatcar_124.json
- extra_vars_openstack_ubuntu_122.json
- extra_vars_openstack_ubuntu_123.json
- extra_vars_openstack_ubuntu_124.json
https://kubernetes.io/releases/patch-releases/
1.22.14
1.23.10
1.24.4
Signed-off-by: Mathias Fechner <fechner@osism.tech>
> Enable new k8s minor versions

- .cirrus.yml
- extra_vars_openstack_ubuntu_125.json
Signed-off-by: Mathias Fechner <fechner@osism.tech>
> Add: k8s version 1.25

- .github/workflows/sync-with-upstream.yml
> github: run "Sync with upstream" only once a day

- .cirrus.yml
- README.md
> Re-enable Ubuntu 20.04 builds

- README.md
Generated with the help of ChatGPT
> README: use tables instead of lists

- README.md
Generated with the help of ChatGPT
> README: use tables instead of lists (pt. 2)

- extra_vars_125.json
- extra_vars_126.json
- extra_vars_127.json
- extra_vars_128.json
- src/update-extra-vars.py
See kubernetes-sigs/image-builder#1280 and https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
> Fix builds

- README.md
Closes osism/k8s-capi-images#226
> README: add link to end of life calender

- .cirrus.yml
Related to a165074a6bb7f96ca3f762a42d368dcce626fa7c
> cirrus: fix push task
